{% set name = "ESMValCore" %}
{% set version = "2.5.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 970ed952c6cd597ff8f9fe5ec5208ded3b064c43451cb989fd55442973baf02b

build:
  # Increment the build number when building a new conda package of the same
  # esmvalcore version, reset to 0 when building a new version.
  number: 0
  # This is noarch but will fail on windows due to missing dependency esmpy.
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - git
    - python >=3.7
    - pip
    - pytest-runner
    - setuptools_scm
  run:
    # esmvaltool
    - python >=3.7
    - iris >=3.1.0
    - python-stratify
    - scipy >=1.6
    # Normally installed via pip:
    - cartopy
    - compilers
    - cftime
    - cf-units >=3.0.0
    - dask
    - defusedxml
    - esgf-pyclient
    - esmpy !=8.1.0
    - geopy
    - fiona
    - fire
    - humanfriendly
    - importlib_resources
    - jinja2
    - myproxyclient
    - nested-lookup
    - netCDF4
    - numpy
    - pandas
    - pillow
    - prov
    - psutil
    - pybtex
    - pyyaml
    - requests
    - shapely
    - yamale

test:
  source_files:
    - tests
    - setup.cfg
  requires:
    # - ESMValTool_sample_data==0.0.3
    - pip
    - pytest
    - pytest-cov
    - pytest-env
    - pytest-flake8
    - pytest-html
    - pytest-metadata
    - pytest-mock
    - pytest-mypy
    - pytest-xdist
    - r-yaml
    # - types-requests
    # - types-pkg_resources
    # - types-PyYAML
  commands:
    - pip install ESMValTool-sample-data types-requests types-pkg_resources types-PyYAML
    - pytest -n 2 --ignore=run_test.py
    - esmvaltool -- --help
    - esmvaltool version
  imports:
    - esmvalcore
    - esmvalcore.cmor
    - esmvalcore.cmor.check
    - esmvalcore.cmor.fix
    - esmvalcore.preprocessor
    - esmvalcore.experimental

about:
  home: https://www.esmvaltool.org
  license: Apache-2.0
  license_file: LICENSE
  summary: 'ESMValCore: A community tool for pre-processing data from Earth system models in CMIP and running analysis scripts.'
  description: 'ESMValCore: A community tool for pre-processing data from Earth system models in CMIP and running analysis scripts.'
  doc_url: https://esmvaltool.readthedocs.io/
  dev_url: https://github.com/ESMValGroup/ESMValCore

extra:
  recipe-maintainers:
    - schlunma
    - zklaus
    - valeriupredoi
    - nielsdrost
    - bouweandela
